### PR TITLE
Contributing in Korean

### PR DESCRIPTION
**Pull request by juho-creator**
Contributing for Korean fellows out there

### CODE REVIEW

**Comment by pionxzh** [comment]
Hi, thanks for contributing!
But you accidentally deleted the original file 🤣

**Comment by juho-creator** [comment]
It's my first time contributing on github so I'm very lost rn XD
I don't know how to fix it so I'll just repost the Contribute_KR.md and Readme_KR.md

**Comment by pionxzh** [comment]
I see. Never mind, I can take care of this.

**Comment by pionxzh** [comment]
I will do it tomorrow

**Comment by juho-creator** [comment]
sanks

**Comment by pionxzh** [comment]
After considering about the ROI and maintenance effort, we will have only have English version of the contribution guide. 

If you want, you can contribute to the UI translation ([en.json](https://github.com/pionxzh/chatgpt-exporter/blob/master/packages/userscript/src/locales/en.json)).

**Pull request closed without merging**
