### PR TITLE
feat(i18n): add spanish translation

### PR DESCRIPTION
**Pull request by ginixsan**
Please check that everything is correct and no messages overlap with the width of container.

### CODE REVIEW

**Comment by pionxzh** [comment]
Ah you might need to `pnpm run lint:fix`

**Comment by ginixsan** [comment]
👍
Saw the run. It’s just a empty lines error at the end

**Comment by ginixsan** [comment]
Fixed the empty spaces

**Comment by pionxzh** [comment]
Thanks!

**Pull request merged**
