### PR TITLE
feat: added support for create_time and update_time metadata parameters per #94

### PR DESCRIPTION
**Pull request by alex-rosenberg35**
Please test first.

### CODE REVIEW

**Comment by pionxzh** [comment]
Thanks!
I have fixed the changes but will put it on hold first.
I would like to let user customize the format of all the date time related variables with syntax like `{create_time:YYYY-MM-DD hh:mm:ss}`. I might work on that in a few days and update this PR to adapt to it.

**Comment by alex-rosenberg35** [comment]
@pionxzh Have you made any progress on allowing a custom time format?  If not, take a look at moment.js (https://momentjs.com/).

**Comment by alex-rosenberg35** [comment]
Great, that works.

**Comment by alex-rosenberg35** [comment]
@pionxzh Could you please accept this PR with the date fixed in ISO format for now?

**Comment by pionxzh** [comment]
Sure, thanks for this.

**Pull request merged**
