### PR TITLE
feat!: rewrite the plugin with API based data source

### PR DESCRIPTION
**Pull request by pionxzh**
## Overview

This pull request introduces a major change to the plugin by rewriting it with an API-based data source. This new implementation brings significant benefits such as improved reliability and flexibility, and lays the groundwork for future enhancements.

## Details
The previous version relied on local HTML parsing, which had several limitations that prevented us from providing advanced features and handling edge cases. By switching to an API-based data source, we can access more complete information about the conversation, enabling us to provide more detailed information to the user.

In addition, we have replaced the previous HTML parsing mechanism with the widely-used markdown parser [`mdast`](https://github.com/syntax-tree/mdast). This improves the plugin's parsing capabilities and allows us to provide more consistent and reliable results.

## Features
- Enhancing content parsing to eliminate the "xxx format is missing in ooo" error (#60, #66)
- Including the timestamp of each post/chat in the HTML export (#54)
- Opening the original chat by clicking the HTML export title (#62)
- Adopting a new user profile picture fetching strategy, potentially fixing issue #53
- Persistent current theme in the URL of HTML export
- Respect the line break in paragraph (#65)
- Improve the styling of HTML export
- Add setting dialog for future features like meta data management

## TODOs
In addition to the improvements above, this PR lays the groundwork for future enhancements, including:
- #39
- #61

### CODE REVIEW

**Comment by Wolf-SO** [comment]
I'm asking because I'm not fluent with JavaScript: Does this rewrite address the JSON data in the `xhr reponse` that was mentioned in #54?

**Comment by pionxzh** [comment]
> I'm asking because I'm not fluent with JavaScript: Does this rewrite address the JSON data in the `xhr reponse` that was mentioned in #54?

exactly 😄

**Comment by Wolf-SO** [comment]
So the proper handling of `\n` embedded in `$.mapping[*].message.content.parts[*]` (I hope that I got the [JSONPath](https://goessner.net/articles/JsonPath/) right) will be part of the rewrite?

**Comment by pionxzh** [comment]
> So the proper handling of `\n` embedded in `$.mapping[*].message.content.parts[*]` (I hope that I got the [JSONPath](https://goessner.net/articles/JsonPath/) right) will be part of the rewrite?

No, at first I guess the process of toHtml will automatically do the break transformation for me. But no, instead, what we need is just the white-space css.

**Pull request merged**
