### PR TITLE
feat: html enhancements: toggle width & latex rendering

### PR DESCRIPTION
**Pull request by moonmd**
HTML exporter enhancements. #264 

1. Added a second toggle for widescreen view
2. Added katex to template.html to render latex. (This is the same engine OpenAI uses.)

The default render was not very readable but after some experimentation I found a format close to the original by adding \displaystyle and \large macros to the preprocessor.

Bare css was not able to center the display math (vs. inline) because identical css is generated for both. I check the nodes on either side of the latex parent for text to determine if it is inline and apply the proper formatting.

### CODE REVIEW

**Comment by moonmd** [comment]
Left '.git' on github link after modifying some test modifications.
The original commit was moved to cleanup-latex branch to preserve it ([b51e4bb](https://github.com/pionxzh/chatgpt-exporter/commit/b51e4bbce1dd5c89d6c6f92814188b93d6f7c829))

I will resubmit it later.  Please let me know your thoughts if you get a chance to look at it

**Comment by moonmd** [comment]
Updated: [a70a8b1](https://github.com/moonmd/chatgpt-exporter/commit/a70a8b1cfe1cef8e6c9f11341b547aab906830e7)

**Comment by pionxzh** [comment]
You can separate the changes for toggle width and latex. I haven't read through the latex part in detail, but using an external script for rendering seems ok.

Question:
1. why do you need to include react in the commit?

**Comment by moonmd** [comment]
OK. I have separated out the width toggle PR #274 
I selected the Cloudflare katex script to match the existing Cloudflare highlight script.

I had to include react because the workflow check failed.

**Pull request closed without merging**
